<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-0BH9N96" failures="1" tests="1" name="Default test" time="6.053" errors="0" timestamp="2024-03-22T06:55:55 IST">
  <testcase classname="org.qa.opencart.tests.LoginTest" name="getloginTest" time="0.018">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void org.qa.opencart.tests.LoginTest.getloginTest(java.lang.String) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: getloginTest([java.lang.String arg0])
Arguments: [(java.lang.String) FebBatch2024@opencart.com,(java.lang.String) 123456]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void org.qa.opencart.tests.LoginTest.getloginTest(java.lang.String) throws java.lang.InterruptedException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: getloginTest([java.lang.String arg0])
Arguments: [(java.lang.String) FebBatch2024@opencart.com,(java.lang.String) 123456]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:918)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getloginTest -->
  <testcase classname="org.qa.opencart.tests.LoginTest" name="loginPageTitleTest" time="0.0">
    <ignored/>
  </testcase> <!-- loginPageTitleTest -->
  <testcase classname="org.qa.opencart.tests.LoginTest" name="loginPageUrlTest" time="0.0">
    <ignored/>
  </testcase> <!-- loginPageUrlTest -->
  <testcase classname="org.qa.opencart.tests.LoginTest" name="loginTest" time="0.0">
    <ignored/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Default test -->
